sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: lob+qvB0YxVYPDy1E84cQJQ1EETdZA9JSOVxAcZY1hbsOlpau935EgEMU8DG2L0FFQmciCrn/VsCbHw8lw4Ee6KGJkprCS7tenCwYrfbphU3DMsFQRhPoIoiqAWpHbXumRRsqNsLviaYepbP/kIAilEyR/QSOL+pEYReqWyl/hv+hcnS5qvclwj0cupGgnNbWet3z5ri6ZpkqzLIghVlVcfoddoD3QsGSJJwRSCw2dWFTVZYNkyriT8BV3P4SpLboW1IRKjH9vIkr0h/LMBxceyChpe5WxzADpkphQMRRvZWSpr8VIQDNA/Zs8XH3g+6fIR875xsxV8gudwm5BmRe6zAljIqVj8FwNuSED5FbYXqDFa6wxy+x+eQrnL2rpzIeL5hAdZ2owrkJ8Ad19CkJ2+juet3LztBV15KfhbFs67JhDk3ercNBtHxlebEI2pV2/G2bHFIB2ZNg3ou3wh33hzNrJjz1bc8xocODDkBByY0MBtJfpxno9b0vtYQbfZtZi6r4Pc+PN43f/kHF8YghtoRlE9CJ/SCuIrcmVsD4S4xm8kp86kHTe+IlE9dPspTzaC1XCgndRQA/Kmwtg4uL/6KlImH5wQ90+dspnvddFV+EorxIAa7TujPh7fRFDWyl8iyBieyFvB1d/hRMUJhRMADW2Y0sDSDAdjGB2d/RIk=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: jPnizB7TO5JOlKe2tJjxSCYggSJ6q2xtIyzufwVzIVpWo7YfTZvWG5/8v2K5gmZy5eGGkfqkhdGfrzoXQWYcVmVszIS8rIg1eHhYktpdyt7FqNcCYO0ENo3RrQ30DGfm7k1dQzVny2znzP5X7/GwxOJ0w6EIeGHsKwj8TeWKQGPVsp7A7/HFNbpGPROvqopZfywSmrDtYjMRP15QiY3aIkmMG5gy3z+P8tExuMt5l1af6e4m3goA0fpog/nW3Kt6SNdojBzEN6UuehaVI7hq7eGyfIRDIHhUXX8uxjbMe9pxKAW/y7QRvlib6Dzj57XYdAwD91z+dhSfY+gCMpZgU3suucCi88M6ulf4Mk8Vh5d0drbCZmPwEEJSfxBM4H/wxBFRbMZQjUTqvwugxgZP161Wtqm4U02UVRbyvnuI2yPVBK2LSmOgkeARJmyNj3selqMyjxN5zqupdepk6Lz6t+x06G84Cj7DaaJas5kO6kF6QM0EZnNwVVwbwMG1RQ6j2DVaz83OshrreSUSWRSeFGr2r62LxAGL7A+rBlE9jmty06C5muf8E+oaEuGH3lBFOavfTBF1CgrDmaCDU9p5cH89Bv9AvEc0p93+TsiFF0eeUeMqjch1pp2QhTsslybXhBeFad0qeHROPBIa2QYbrmnzNU/DySflmyFAnnKM2so=
